- name: "Gray"
  primary: "#09090B"
- name: Red
  primary: "#EF4444"
- name: Orange
  primary: "#F97316"
- name: Amber
  primary: "#F59E0B"
- name: Yellow
  primary: "#EAB308"
- name: Lime
  primary: "#84CC16"
- name: Green
  primary: "#22C55E"
- name: Cyan
  primary: "#06B6D4"
- name: Sky
  primary: "#0EA5E9"
- name: Blue
  primary: "#3B82F6"
- name: Indigo
  primary: "#6366F1"
- name: Violet
  primary: "#8B5CF6"
- name: Purple
  primary: "#A855F7"
- name: Fuchsia
  primary: "#D946EF"
- name: Pink
  primary: "#EC4899"
