default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

queue: &queue
  <<: *default
  migrrations: db/queue_migrations

development:
  primary:
    <<: *default
    database: picoletter_development
  queue:
    <<: *queue
    database: picoletter_development_queue

test:
  primary:
    <<: *default
    database: picoletter_test
  queue:
    <<: *queue
    database: picoletter_test_queue

production:
  primary:
    <<: *default
    database: picoletter_production
    username: picoletter
    password: <%= ENV["PICOLETTER_DATABASE_PASSWORD"] %>
  queue:
    <<: *queue
    database: picoletter_production_queue
    password: <%= ENV["PICOLETTER_DATABASE_PASSWORD"] %>
