default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: picoletter_development
  queue:
    <<: *default
    database: picoletter_development_queue
    migrrations: db/queue_migrations

test:
  primary:
    <<: *default
    database: picoletter_test
  queue:
    <<: *default
    database: picoletter_test_queue
    migrrations: db/queue_migrations

production:
  primary:
    <<: *default
    database: picoletter_production
    username: picoletter
    password: <%= ENV["PICOLETTER_DATABASE_PASSWORD"] %>
  queue:
    <<: *default
    database: picoletter_production_queue
    password: <%= ENV["PICOLETTER_DATABASE_PASSWORD"] %>
    migrrations: db/queue_migrations
