default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        send_published_post:
          class: SendSchedulePostJob
          schedule: every minute
        verify_dns:
          class: VerifyDNSRecordsJob
          schedule: every week
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
