default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        send_published_post:
          class: SendScheduledPostJob
          schedule: every minutes
        verify_dns:
          class: VerifyDNSRecordsJob
          schedule: 0 0 */3 * *
        periodic_litestream_backup_verfication_job:
          class: Litestream::VerificationJob
          schedule: every day at 1am EST

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
