name: Run Tests on Pull Request

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec
